[tool.poetry]
name = "fc模拟器"
version = "0.1.0"
description = ""
authors = ["Dream <1147262934@qq.com>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
